//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSale
    {
        public long SalesId { get; set; }
        public string RecordIDs { get; set; }
        public string Company { get; set; }
        public string Prefix { get; set; }
        public string First { get; set; }
        public string Middle { get; set; }
        public string Last { get; set; }
        public string BuyerEmail { get; set; }
        public string Suffix { get; set; }
        public string Title { get; set; }
        public string PROPERTY_INDICATOR { get; set; }
        public string MUNICIPALITY_NAME { get; set; }
        public string OWNER_CORPORATE_INDICATOR { get; set; }
        public string LAND_USE { get; set; }
        public string OWNER_NAME { get; set; }
        public string OWNER_NAME_2 { get; set; }
        public string OWNER_NAME_3 { get; set; }
        public string ABSENTEE_OWNER { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Zip4 { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string SCF { get; set; }
        public string ADDRESS_INDICATOR { get; set; }
        public string HOUSE_NUMBER_PREFIX { get; set; }
        public string HOUSE_NUMBER { get; set; }
        public string HOUSE_NUMBER_SUFFIX { get; set; }
        public string DIRECTION { get; set; }
        public string STREET_NAME { get; set; }
        public string MODE { get; set; }
        public string QUADRANT { get; set; }
        public string CARRIER_CODE { get; set; }
        public string HOUSE_NUMBER_PREFIX2 { get; set; }
        public string HOUSE_NUMBER2 { get; set; }
        public string HOUSE_NUMBER_SUFFIX2 { get; set; }
        public string DIRECTION2 { get; set; }
        public string STREET_NAME2 { get; set; }
        public string MODE2 { get; set; }
        public string QUADRANT2 { get; set; }
        public string CARRIER_CODE2 { get; set; }
        public string APT_UNIT_NUMBER2 { get; set; }
        public string CITY2 { get; set; }
        public string STATE2 { get; set; }
        public string ZIP_CODE2 { get; set; }
        public string TOTAL_VALUE_CALCULATED { get; set; }
        public string LAND_VALUE_CALCULATED { get; set; }
        public string IMPROVEMENT_VALUE_CALCULATED { get; set; }
        public string TOTAL_VALUE_CALCULATED_IND { get; set; }
        public string LAND_VALUE_CALCULATED_IND { get; set; }
        public string IMPROVEMENT_VALUE_CALCULATED_IND { get; set; }
        public string ASSD_TOTAL_VALUE { get; set; }
        public string ASSD_LAND_VALUE { get; set; }
        public string ASSD_IMPROVEMENT_VALUE { get; set; }
        public string ASSD_YEAR { get; set; }
        public string MKT_TOTAL_VALUE { get; set; }
        public string MKT_LAND_VALUE { get; set; }
        public string MKT_IMPROVEMENT_VALUE { get; set; }
        public string APPR_TOTAL_VALUE { get; set; }
        public string APPR_LAND_VALUE { get; set; }
        public string APPR_IMPROVEMENT_VALUE { get; set; }
        public string TAX_AMOUNT { get; set; }
        public string TAX_YEAR { get; set; }
        public string DOCUMENT_YEAR { get; set; }
        public string SALES_DEED_CATEGORY_TYPE { get; set; }
        public string RECORDING_DATE { get; set; }
        public string SALE_DATE { get; set; }
        public string SALE_PRICE { get; set; }
        public string SALE_CODE { get; set; }
        public string SELLER_NAME { get; set; }
        public string SellerEmail { get; set; }
        public string SALES_TRANSACTION_CODE { get; set; }
        public string RESIDENTIAL_MODEL_INDICATOR { get; set; }
        public string PRIOR_DOCUMENT_YEAR { get; set; }
        public string PRIOR_SLS_DEED_CATEGORY_TYPE { get; set; }
        public string PRIOR_RECORDING_DATE { get; set; }
        public string PRIOR_SALE_DATE { get; set; }
        public string PRIOR_SALE_PRICE { get; set; }
        public string PRIOR_SALE_CODE { get; set; }
        public string PRIOR_DEED_TYPE { get; set; }
        public string FRONT_FOOTAGE { get; set; }
        public string DEPTH_FOOTAGE { get; set; }
        public string ACRES { get; set; }
        public string LAND_SQUARE_FOOTAGE { get; set; }
        public string UNIVERSAL_BUILDING_SQUARE_FEET { get; set; }
        public string BUILDING_SQUARE_FEET_IND { get; set; }
        public string BUILDING_SQUARE_FEET { get; set; }
        public string LIVING_SQUARE_FEET { get; set; }
        public string GROUND_FLOOR_SQUARE_FEET { get; set; }
        public string GROSS_SQUARE_FEET { get; set; }
        public string ADJUSTED_GROSS_SQUARE_FEET { get; set; }
        public string BASEMENT_SQUARE_FEET { get; set; }
        public string GARAGE_PARKING_SQUARE_FEET { get; set; }
        public string YEAR_BUILT { get; set; }
        public string EFFECTIVE_YEAR_BUILT { get; set; }
        public string BEDROOMS { get; set; }
        public string TOTAL_ROOMS { get; set; }
        public string TOTAL_BATHS_CALCULATED { get; set; }
        public string TOTAL_BATHS { get; set; }
        public string FULL_BATHS { get; set; }
        public string HALF_BATHS { get; set; }
        public string QTR_BATHS1 { get; set; }
        public string QTR_BATHS3 { get; set; }
        public string BATH_FIXTURES { get; set; }
        public string AIR_CONDITIONING { get; set; }
        public string BASEMENT_FINISH { get; set; }
        public string BLDG_CODE { get; set; }
        public string BLDG_IMPV_CODE { get; set; }
        public string CONDITION { get; set; }
        public string CONSTRUCTION_TYPE { get; set; }
        public string EXTERIOR_WALLS { get; set; }
        public string FIREPLACE_IND { get; set; }
        public string FIREPLACE_NUMBER { get; set; }
        public string FIREPLACE_TYPE { get; set; }
        public string FOUNDATION { get; set; }
        public string FLOOR { get; set; }
        public string FRAME { get; set; }
        public string GARAGE { get; set; }
        public string HEATING { get; set; }
        public string MOBILE_HOME_IND { get; set; }
        public string PARKING_SPACES { get; set; }
        public string PARKING_TYPE { get; set; }
        public string POOL { get; set; }
        public string POOL_CODE { get; set; }
        public string QUALITY { get; set; }
        public string ROOF_COVER { get; set; }
        public string ROOF_TYPE { get; set; }
        public string STORIES_CODE { get; set; }
        public string STORIES_NUMBER { get; set; }
        public string STYLE { get; set; }
        public string UNITS_NUMBER { get; set; }
        public string ELECTRIC_ENERGY { get; set; }
        public string FUEL { get; set; }
        public string SEWER { get; set; }
        public string WATER { get; set; }
        public string OWNER_OWNERSHIP_RIGHTS_CODE { get; set; }
        public string SUBDIVISION_NAME { get; set; }
        public string HOMESTEAD_EXEMPT2 { get; set; }
        public string VETERANS_EXEMPTION { get; set; }
        public string DISABLED_EXEMPTION { get; set; }
        public string WIDOW_EXEMPTION { get; set; }
        public string AGED_EXEMPTION { get; set; }
        public string CONSTRUCTION_CD { get; set; }
        public string STYLE_CODE { get; set; }
        public string SELLER_CARRY_BACK { get; set; }
        public string SITUS_LATITUDE { get; set; }
        public string SITUS_LONGITUE { get; set; }
        public string LOAN_TO_VALUE { get; set; }
        public string CENSUS_TRACT { get; set; }
        public string ZONING { get; set; }
        public string RANGE { get; set; }
        public string TOWNSHIP { get; set; }
        public string SECTION { get; set; }
        public string QUARTER_SECTION { get; set; }
        public string HOMESTEAD_EXEMPT1 { get; set; }
        public string COUNTY_USE_1 { get; set; }
        public string COUNTY_USE_2 { get; set; }
        public string NUMBER_OF_BUILDINGS { get; set; }
        public string ListingId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
